### ISSUE TITLE
Everything vanishes on filtering levels using Google Chrome

### ISSUE THREAD

**Issue by bodhwani** [SeanPrashad/leetcode-patterns#40] opened 2020-07-17 06:31 UTC
As I filter anything, everything vanishes. 
It is working fine on safari, but not on Google Chrome. Please check whats the issue.

**Comment by SeanPrashad** [comment] 2020-07-17 12:35
Hey @bodhwani - thanks for reaching out!

Are you able to tell me the following?

- Version of Chrome
- Are you on mobile?
- Have you "checked" off any questions as completed?
- What is the minimum filtering options for "everything to vanish"? For example, if you select only "Medium" questions, do all questions dissapear? What happens if you select "Medium" difficulty with the company "Google"?

These will give me a head start into debugging what might be happening - thanks!

**Comment by bodhwani** [comment] 2020-07-17 15:58
Version is 
"Version 83.0.4103.116 (Official Build) (64-bit)"
I am on Mac OS
Mark question: Yes I tried. It is not working
If I try any filter, everything vanishes. Hope that helps!

**Comment by SeanPrashad** [comment] 2020-07-17 17:11
Thanks for that info @bodhwani - my first instinct is that I broke something in [this patch](https://github.com/SeanPrashad/leetcode-patterns/pull/35), which automatically resizes the local storage array used to keep track of which questions have been completed when you click a checkbox.

One way would be to completely reset that array that from within Chrome, but that means you would start with every question unchecked - this will be a last resort.

Could you please browse to https://seanprashad.com/leetcode-patterns/ using [Incognito Mode](https://support.google.com/chrome/answer/95464?co=GENIE.Platform%3DDesktop&hl=en) and see if you can load the website AND filter by `Medium` for question difficulty?

Let me know if that helps and if not, we'll try some other routes to debug since I can't reproduce the issue on my end.

**Comment by bodhwani** [comment] 2020-07-17 17:20
It works fine on Incognito Mode, but I cannot keep track of anything as I close the tab. Is there any other alternative?
Btw, how to reset the array within Chrome? @SeanPrashad

**Comment by SeanPrashad** [comment] 2020-07-17 17:26
Awesome @bodhwani - let's reset the array within Chrome!

1. Please open up a regular Google Chrome browser
1. Press <kbd>Cmd</kbd> + <kbd>Option</kbd> + <kbd>J</kbd> to open Developer Tools
1. Navigate to the `Application` tab as shown below:
![image](https://user-images.githubusercontent.com/13009507/87813863-b3dfde80-c830-11ea-9e53-f5072b892b0a.png)
1. From the left-hand side, left click the arrow near **Local Storage** under **Storage**:
![image](https://user-images.githubusercontent.com/13009507/87813921-d245da00-c830-11ea-8bff-5e212f7937dc.png)
1. Select `https://seanprashad.com` and delete the `Key` called `checked` using <kbd>Backspace</kbd>
1. Refresh the web page and try to filter by any column

Please let me know if you get stuck!

**Comment by bodhwani** [comment] 2020-07-17 21:09
Nope. Still, it is not working :(

**Comment by SeanPrashad** [comment] 2020-07-17 21:14
OK - let's try another way of deleting it:

1. Open `chrome://settings/siteData` in a new tab
1. In the top right hand corner, search for `seanprashad`:
![image](https://user-images.githubusercontent.com/13009507/87831142-a4708d80-c850-11ea-9bd1-2ede00481623.png)
1. Click the trash icon to delete local storage for the leetcode patterns website
1. Next, browse to https://seanprashad.com/leetcode-patterns/
1. Press <kbd>Shift</kbd> + <kbd>Cmd</kbd> + <kbd>R</kbd> to refresh the page without using cache

Please let me know if this works!

**Comment by bodhwani** [comment] 2020-07-17 21:48
Still not working
Errors:
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by SeanPrashad** [comment] 2020-07-17 21:57
Hmm.. this is super weird and that error message is for React but doesn't give us much to work with unfortunately 🤔 

For now, please use the website in another web browser and keep track of your completed questions in a document of some kind - I need to take a look at the changes I've made recently in more detail and see if I can figure out the problem and push a new patched version

**Comment by SeanPrashad** [comment] 2020-07-17 22:35
@bodhwani I noticed that you are on an old version of Google Chrome - can you please update it as per these instructions: https://support.google.com/chrome/answer/95414?co=GENIE.Platform%3DDesktop&hl=en

The version I have is `Version 84.0.4147.89 (Official Build) (64-bit)`:

![image](https://user-images.githubusercontent.com/13009507/87835832-4cd81f00-c85c-11ea-97a2-9e9fe0f3dada.png)

**Comment by SeanPrashad** [comment] 2020-07-20 22:38
Hi @bodhwani - please let me know if this is still an issue after persisting, otherwise I'll consider this fixed and close the issue

**Comment by bodhwani** [comment] 2020-07-21 17:00
It didnt solve the issue.

**Comment by SeanPrashad** [comment] 2020-07-21 22:53
Hmm this is really strange.. I have to do some more digging and think of what else we can try - please use another browser for the time being, ty!

**Comment by SeanPrashad** [comment] 2020-07-24 19:37
Hey @bodhwani - another idea popped into my head to try.

Can you delete cookies for https://seanprashad.com/leetcode-patterns/ by doing the following:

1. Open Chrome and browse to https://seanprashad.com/leetcode-patterns/
1. Click on the lock icon to the left of the URL bar:

![image](https://user-images.githubusercontent.com/13009507/88428748-77c5f400-cdc3-11ea-81f2-d1e16b7ad454.png)

1. Click on **Cookies**
1. Remove all cookies that you see here
1. Close Google Chrome completely
1. Reopen Google Chrome and try to filter via any dropdown list
1. Reply back with your findings

**Comment by bodhwani** [comment] 2020-07-25 20:16
Still didn't work :(

**Closed** 2020-11-29 05:16 UTC
Labels: bug 👾
