### ISSUE TITLE
Filters should not reset after a refresh/new session

### ISSUE THREAD

**Issue by OrdinaryGecko** [seanprashad/leetcode-patterns#164] opened 2022-03-10 08:52 UTC
When I refresh the page, my chosen filters like patterns, difficulty etc. gets reset. Is it possible to retrieve last used filters?

**Comment by seanprashad** [comment] 2022-03-10 17:40
Duplicate of https://github.com/seanprashad/leetcode-patterns/issues/87

**Comment by steviekong** [comment] 2022-04-04 08:54
This PR should resolve the issue

**Closed** 2022-04-04 19:04 UTC
Labels: feature request 💬, open to contributors 📬
